// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx'
import * as $_500 from './routes/_500.tsx'
import * as $_app from './routes/_app.tsx'
import * as $api_auth_login from './routes/api/auth/login.ts'
import * as $api_auth_session from './routes/api/auth/session.ts'
import * as $api_content_meta from './routes/api/content-meta.ts'
import * as $api_docs from './routes/api/docs.ts'
import * as $api_downloads from './routes/api/downloads.ts'
import * as $api_ping from './routes/api/ping.ts'
import * as $api_render_markdown from './routes/api/render-markdown.ts'
import * as $api_templates from './routes/api/templates.ts'
import * as $index from './routes/index.tsx'
import * as $login from './routes/login.tsx'
import * as $navbar_demo from './routes/navbar-demo.tsx'
import * as $panel_account from './routes/panel/account.tsx'
import * as $panel_index from './routes/panel/index.tsx'
import * as $panel_mail from './routes/panel/mail.tsx'
import * as $register from './routes/register.tsx'
import * as $AccountDropdown from './islands/AccountDropdown.tsx'
import * as $AskAIButton from './islands/AskAIButton.tsx'
import * as $Counter from './islands/Counter.tsx'
import * as $LoginForm from './islands/LoginForm.tsx'
import * as $MobileMenu from './islands/MobileMenu.tsx'
import * as $Navbar from './islands/Navbar.tsx'
import * as $RegisterForm from './islands/RegisterForm.tsx'
import * as $SearchDialog from './islands/SearchDialog.tsx'
import * as $panel_Header from './islands/panel/Header.tsx'
import * as $panel_PanelLayout from './islands/panel/PanelLayout.tsx'
import * as $panel_Sidebar from './islands/panel/Sidebar.tsx'
import type { Manifest } from '$fresh/server.ts'

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_500.tsx': $_500,
    './routes/_app.tsx': $_app,
    './routes/api/auth/login.ts': $api_auth_login,
    './routes/api/auth/session.ts': $api_auth_session,
    './routes/api/content-meta.ts': $api_content_meta,
    './routes/api/docs.ts': $api_docs,
    './routes/api/downloads.ts': $api_downloads,
    './routes/api/ping.ts': $api_ping,
    './routes/api/render-markdown.ts': $api_render_markdown,
    './routes/api/templates.ts': $api_templates,
    './routes/index.tsx': $index,
    './routes/login.tsx': $login,
    './routes/navbar-demo.tsx': $navbar_demo,
    './routes/panel/account.tsx': $panel_account,
    './routes/panel/index.tsx': $panel_index,
    './routes/panel/mail.tsx': $panel_mail,
    './routes/register.tsx': $register,
  },
  islands: {
    './islands/AccountDropdown.tsx': $AccountDropdown,
    './islands/AskAIButton.tsx': $AskAIButton,
    './islands/Counter.tsx': $Counter,
    './islands/LoginForm.tsx': $LoginForm,
    './islands/MobileMenu.tsx': $MobileMenu,
    './islands/Navbar.tsx': $Navbar,
    './islands/RegisterForm.tsx': $RegisterForm,
    './islands/SearchDialog.tsx': $SearchDialog,
    './islands/panel/Header.tsx': $panel_Header,
    './islands/panel/PanelLayout.tsx': $panel_PanelLayout,
    './islands/panel/Sidebar.tsx': $panel_Sidebar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
