// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx'
import * as $_500 from './routes/_500.tsx'
import * as $_app from './routes/_app.tsx'
import * as $api_auth_login from './routes/api/auth/login.ts'
import * as $api_auth_mfa_disable_index from './routes/api/auth/mfa/disable/index.ts'
import * as $api_auth_mfa_setup_index from './routes/api/auth/mfa/setup/index.ts'
import * as $api_auth_mfa_status_index from './routes/api/auth/mfa/status/index.ts'
import * as $api_auth_mfa_verify_index from './routes/api/auth/mfa/verify/index.ts'
import * as $api_auth_session from './routes/api/auth/session.ts'
import * as $api_content_meta from './routes/api/content-meta.ts'
import * as $api_docs from './routes/api/docs.ts'
import * as $api_downloads from './routes/api/downloads.ts'
import * as $api_ping from './routes/api/ping.ts'
import * as $api_render_markdown from './routes/api/render-markdown.ts'
import * as $api_templates from './routes/api/templates.ts'
import * as $download_segments_index from './routes/download/[...segments]/index.tsx'
import * as $download_index from './routes/download/index.tsx'
import * as $email_verification from './routes/email-verification.tsx'
import * as $index from './routes/index.tsx'
import * as $login from './routes/login.tsx'
import * as $logout from './routes/logout.tsx'
import * as $navbar_demo from './routes/navbar-demo.tsx'
import * as $panel_account from './routes/panel/account.tsx'
import * as $panel_agent from './routes/panel/agent.tsx'
import * as $panel_api from './routes/panel/api.tsx'
import * as $panel_appearance from './routes/panel/appearance.tsx'
import * as $panel_index from './routes/panel/index.tsx'
import * as $panel_ldp from './routes/panel/ldp.tsx'
import * as $panel_mail from './routes/panel/mail.tsx'
import * as $panel_management from './routes/panel/management.tsx'
import * as $panel_subscription from './routes/panel/subscription.tsx'
import * as $register from './routes/register.tsx'
import * as $AccountDropdown from './islands/AccountDropdown.tsx'
import * as $AskAIButton from './islands/AskAIButton.tsx'
import * as $Counter from './islands/Counter.tsx'
import * as $EmailVerificationForm from './islands/EmailVerificationForm.tsx'
import * as $LoginForm from './islands/LoginForm.tsx'
import * as $LogoutHandler from './islands/LogoutHandler.tsx'
import * as $MobileMenu from './islands/MobileMenu.tsx'
import * as $Navbar from './islands/Navbar.tsx'
import * as $RegisterForm from './islands/RegisterForm.tsx'
import * as $SearchDialog from './islands/SearchDialog.tsx'
import * as $UserMenu from './islands/UserMenu.tsx'
import * as $home_ShowcaseCarousel from './islands/home/ShowcaseCarousel.tsx'
import * as $panel_Header from './islands/panel/Header.tsx'
import * as $panel_PanelLayout from './islands/panel/PanelLayout.tsx'
import * as $panel_Sidebar from './islands/panel/Sidebar.tsx'
import type { Manifest } from '$fresh/server.ts'

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_500.tsx': $_500,
    './routes/_app.tsx': $_app,
    './routes/api/auth/login.ts': $api_auth_login,
    './routes/api/auth/mfa/disable/index.ts': $api_auth_mfa_disable_index,
    './routes/api/auth/mfa/setup/index.ts': $api_auth_mfa_setup_index,
    './routes/api/auth/mfa/status/index.ts': $api_auth_mfa_status_index,
    './routes/api/auth/mfa/verify/index.ts': $api_auth_mfa_verify_index,
    './routes/api/auth/session.ts': $api_auth_session,
    './routes/api/content-meta.ts': $api_content_meta,
    './routes/api/docs.ts': $api_docs,
    './routes/api/downloads.ts': $api_downloads,
    './routes/api/ping.ts': $api_ping,
    './routes/api/render-markdown.ts': $api_render_markdown,
    './routes/api/templates.ts': $api_templates,
    './routes/download/[...segments]/index.tsx': $download_segments_index,
    './routes/download/index.tsx': $download_index,
    './routes/email-verification.tsx': $email_verification,
    './routes/index.tsx': $index,
    './routes/login.tsx': $login,
    './routes/logout.tsx': $logout,
    './routes/navbar-demo.tsx': $navbar_demo,
    './routes/panel/account.tsx': $panel_account,
    './routes/panel/agent.tsx': $panel_agent,
    './routes/panel/api.tsx': $panel_api,
    './routes/panel/appearance.tsx': $panel_appearance,
    './routes/panel/index.tsx': $panel_index,
    './routes/panel/ldp.tsx': $panel_ldp,
    './routes/panel/mail.tsx': $panel_mail,
    './routes/panel/management.tsx': $panel_management,
    './routes/panel/subscription.tsx': $panel_subscription,
    './routes/register.tsx': $register,
  },
  islands: {
    './islands/AccountDropdown.tsx': $AccountDropdown,
    './islands/AskAIButton.tsx': $AskAIButton,
    './islands/Counter.tsx': $Counter,
    './islands/EmailVerificationForm.tsx': $EmailVerificationForm,
    './islands/LoginForm.tsx': $LoginForm,
    './islands/LogoutHandler.tsx': $LogoutHandler,
    './islands/MobileMenu.tsx': $MobileMenu,
    './islands/Navbar.tsx': $Navbar,
    './islands/RegisterForm.tsx': $RegisterForm,
    './islands/SearchDialog.tsx': $SearchDialog,
    './islands/UserMenu.tsx': $UserMenu,
    './islands/home/ShowcaseCarousel.tsx': $home_ShowcaseCarousel,
    './islands/panel/Header.tsx': $panel_Header,
    './islands/panel/PanelLayout.tsx': $panel_PanelLayout,
    './islands/panel/Sidebar.tsx': $panel_Sidebar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
