/**
 * Download manifest loader for Fresh + Deno
 *
 * This module loads download listings from pre-built static JSON files.
 * No runtime filesystem access needed - all data is generated at build time.
 */

import type { DirListing } from '../types/download.ts'

// Import pre-built manifests from static directory
// These are generated by scripts/fetch-dl-index.ts during build
let downloadListings: DirListing[] = []

/**
 * Load download listings from static build directory
 * This is async to support both server and edge environments
 */
async function loadListings(): Promise<DirListing[]> {
  try {
    // Try to load from build artifacts first
    const manifestPath = new URL('../static/_build/dl-index/all.json', import.meta.url).pathname
    const content = await Deno.readTextFile(manifestPath)
    const parsed = JSON.parse(content)
    return Array.isArray(parsed) ? (parsed as DirListing[]) : []
  } catch {
    // Fallback to empty array if not built yet
    console.warn('[download-manifest] Build artifacts not found. Run `deno task build` first.')
    return []
  }
}

// Initialize listings
downloadListings = await loadListings()

export const DOWNLOAD_LISTINGS: DirListing[] = downloadListings

export function getDownloadListings(): DirListing[] {
  return DOWNLOAD_LISTINGS
}

/**
 * Refresh listings (useful for development)
 */
export async function refreshDownloadListings(): Promise<void> {
  downloadListings = await loadListings()
}
